/* Adrita Khan — shared search index, loaded by every page */
window.AK_SEARCH_IDX = [

  /* ── HOME ── */
  {page:"index.html",pageLabel:"Home",title:"Adrita Khan — About",
   snippet:"PhD Aspirant in Astrophysics & Cosmology. Graduate of Universiti Sains Malaysia (USM), BSc Physics with Minor in Astronomy. Interests in Theoretical and Observational Cosmology, Large-Scale Structure, Dark Matter, Dark Energy, Modified Gravity, Cosmic Inflation, Machine Learning.",
   keywords:"adrita khan home about phd aspirant astrophysics cosmology usm universiti sains malaysia bsc physics astronomy theoretical observational large scale structure dark matter dark energy modified gravity cosmic inflation machine learning bangladesh"},
  {page:"index.html",pageLabel:"Home",title:"Key Research Areas",
   snippet:"Cosmology, Large-Scale Structure, Dark Energy, Dark Matter, Modified Gravity, Machine Learning, Cosmic Inflation, Multimessenger Astrophysics, Astroparticle Physics, Astrostatistics.",
   keywords:"home research areas cosmology large scale structure dark energy dark matter modified gravity machine learning cosmic inflation multimessenger astroparticle physics astrostatistics"},
  {page:"index.html",pageLabel:"Home",title:"Education — BSc Physics (Honours), USM",
   snippet:"Bachelor of Science (Honours) in Physics, Universiti Sains Malaysia, School of Physics, Penang, Malaysia. Graduated 2023. Major: Physics, Minor: Astronomy. Dean's List (3 semesters). Honours Research Project.",
   keywords:"home education bsc bachelor science honours physics universiti sains malaysia usm penang 2023 major physics minor astronomy dean's list honours research project graduated"},
  {page:"index.html",pageLabel:"Home",title:"Featured Research — Modified Gravity Cross-Correlation",
   snippet:"Galaxy–galaxy power spectra (Cℓgg) and galaxy–CMB lensing cross-power spectra (Cℓκg) using nDGP, e-mantis, Bacco emulators. Forecasting LSST/DESC constraints on f(R) and DGP gravity.",
   keywords:"home featured research modified gravity cross-correlation cmb lensing galaxy power spectra ndgp e-mantis bacco emulator lsst desc f(r) dgp lambda cdm constraints forecast"},
  {page:"index.html",pageLabel:"Home",title:"Publication — E-PCN Jet Tagging (arXiv:2512.07420)",
   snippet:"Explainable Particle Chebyshev Networks (E-PCN) for jet classification in high-energy collider experiments. Graph neural network with Grad-CAM explainability. arXiv:2512.07420, December 2025.",
   keywords:"home publication e-pcn jet tagging explainable particle chebyshev networks arxiv 2512.07420 graph neural network grad-cam kinematic features high energy physics hep preprint 2025"},
  {page:"index.html",pageLabel:"Home",title:"Contact & Social Links",
   snippet:"GitHub: Adrita-Khan | ORCID: 0009-0000-9304-8895 | Twitter: @Adrita_ | ResearchGate | Google Scholar | LinkedIn",
   keywords:"home contact github adrita-khan orcid 0009-0000-9304-8895 twitter adrita_ researchgate google scholar linkedin social email"},
  {page:"index.html",pageLabel:"Home",title:"Surveys & Observatories",
   snippet:"Vera C. Rubin Observatory LSST/DESC, Euclid mission, DESI, Simons Observatory, CMB-S4, Atacama Cosmology Telescope (ACT).",
   keywords:"home surveys observatories vera rubin lsst desc euclid desi simons observatory cmb-s4 atacama cosmology telescope act next generation"},

  /* ── EDUCATION ── */
  {page:"education.html",pageLabel:"Education",title:"BSc Physics (Honours) — Universiti Sains Malaysia (USM)",
   snippet:"Bachelor of Science (Honours) in Physics. School of Physics, USM, Penang, Malaysia. Graduated 2023. Major: Physics, Minor: Astronomy. Dean's List Semesters II, III, VI. Honours Research Project.",
   keywords:"education bsc bachelor science honours physics usm universiti sains malaysia penang 2023 major physics minor astronomy dean's list semesters ii iii vi honours research project graduated"},
  {page:"education.html",pageLabel:"Education",title:"Technical & Computational Skills",
   snippet:"Python, MCMC, Bayesian inference, TensorFlow, PyTorch, JAX, HEALPix, Astropy, Astroquery, NumPy, SciPy, Matplotlib, TOPCAT, DS9, MPI, OpenMP, SLURM, PBS, GPU computing, Git, GitHub, Jupyter, HDF5, FITS.",
   keywords:"education skills python mcmc bayesian inference tensorflow pytorch jax healpy astropy astroquery numpy scipy matplotlib topcat ds9 mpi openmp slurm pbs gpu computing git github jupyter hdf5 fits overleaf vectorization hpc"},
  {page:"education.html",pageLabel:"Education",title:"Language Skills",
   snippet:"Bengali (Native C2), English (Bilingual C2), Hindi (B1 Intermediate), German (A2 Elementary), Malay (A1 Beginner).",
   keywords:"education languages bengali english hindi german malay native bilingual c2 intermediate elementary beginner"},
  {page:"education.html",pageLabel:"Education",title:"Wi-STEM Bangladesh Summer Research Internship (2021)",
   snippet:"Machine Learning in Astrophysics. Photometric Redshifts using Gaussian Processes from astronomical survey data. Supervisor: Dr. Tonima Tasnim Ananna. Jul–Dec 2021.",
   keywords:"education wi-stem bangladesh summer research internship machine learning astrophysics photometric redshifts gaussian processes astronomical survey tonima tasnim ananna 2021 jul dec"},
  {page:"education.html",pageLabel:"Education",title:"Astronomy Club — Universiti Sains Malaysia",
   snippet:"Elected Student Representative (Exco) 2019–2020. Stargazing sessions, public outreach, workshops. Represented students from 10+ nationalities. Cross-cultural collaboration.",
   keywords:"education astronomy club universiti sains malaysia exco elected student representative 2019 2020 stargazing public outreach workshops cross-cultural nationalities physics colloquia coffee talks"},
  {page:"education.html",pageLabel:"Education",title:"Future Graduate Studies — PhD in Astrophysics",
   snippet:"PhD Aspirant in Astrophysics and Cosmology. Research interests: Observational Cosmology, Large-Scale Structure, Modified Gravity, Dark Matter, Dark Energy, High-Energy Astrophysics, Galaxy Evolution, Astrostatistics, Machine Learning.",
   keywords:"education future graduate studies phd astrophysics cosmology observational large scale structure modified gravity dark matter dark energy high energy galaxy evolution astrostatistics machine learning upcoming planning"},
  {page:"education.html",pageLabel:"Education",title:"Non-Technical Skills",
   snippet:"Scientific Writing, Science Outreach & Communication, Public Speaking, Cross-Cultural Collaboration, Research Coordination.",
   keywords:"education non-technical skills scientific writing science outreach communication public speaking cross-cultural collaboration research coordination"},
  {page:"education.html",pageLabel:"Education",title:"Coursework — Physics & Astronomy",
   snippet:"Quantum mechanics, astrophysics, mathematical physics, computational methods, astronomy, observational techniques. Developed expertise over 8 semesters.",
   keywords:"education coursework quantum mechanics astrophysics mathematical physics computational methods astronomy observational techniques semesters"},

  /* ── PUBLICATIONS ── */
  {page:"publications.html",pageLabel:"Publications",title:"RGC-BENT: Bent Radio Galaxy Classification (IEEE ICIP 2025)",
   snippet:"Novel dataset for bent radio galaxy classification. Mir Sazzat Hossain, Khan Muhammad Bin Asad, Payaswini Saikia, Adrita Khan et al. IEEE ICIP 2025, Anchorage, Alaska. NAT, WAT sources.",
   keywords:"publications rgc-bent bent radio galaxy classification dataset ieee icip 2025 mir sazzat hossain khan muhammad bin asad payaswini saikia adrita khan deep learning nat wat anchorage alaska ieee xplore conference image processing"},
  {page:"publications.html",pageLabel:"Publications",title:"E-PCN: Jet Tagging with Explainable Particle Chebyshev Networks (arXiv:2512.07420)",
   snippet:"Extends Particle Chebyshev Network (PCN) for interpretable jet classification. Four graph representations weighted by angular separation Δ, transverse momentum kT, momentum fraction z, invariant mass m². Grad-CAM explainability. December 2025.",
   keywords:"publications e-pcn jet tagging explainable particle chebyshev networks kinematic features arxiv 2512.07420 preprint graph neural network grad-cam angular separation delta transverse momentum kt momentum fraction z invariant mass high energy physics hep-ph 2025 december islam khan hossain"},
  {page:"publications.html",pageLabel:"Publications",title:"BibTeX Citations",
   snippet:"BibTeX citation entries available for all publications. Copy for LaTeX documents. arXiv identifiers, DOI, IEEE links.",
   keywords:"publications bibtex citation latex copy cite references arxiv doi ieee"},

  /* ── RESEARCH & PROJECTS ── */
  {page:"research.html",pageLabel:"Research & Projects",title:"R1 — Modified Gravity Cross-Correlation",
   snippet:"Testing Modified Gravity via galaxy clustering and CMB lensing cross-correlation. f(R) gravity, DGP gravity. LSST/DESC, Simons Observatory. Fisher matrix forecasting, MCMC, fast emulators. Supervisors: Dr. Tanveer Karim, Dr. Georgios Valogiannis.",
   keywords:"research r1 modified gravity cross-correlation galaxy clustering cmb lensing f(r) dgp gravity lsst desc simons observatory fisher matrix mcmc emulator tanveer karim georgios valogiannis large scale structure cosmology angular power spectrum"},
  {page:"research.html",pageLabel:"Research & Projects",title:"R2 — E-PCN: Interaction Feature Guided Jet Tagging",
   snippet:"Explainable Particle Chebyshev Network using physics-motivated interaction features (ln Δ, ln kT, ln z, ln m²) to classify jets on CERN Open Data (JetClass). QCD-informed machine learning.",
   keywords:"research r2 e-pcn jet tagging interaction features explainable particle chebyshev network cern open data jetclass qcd machine learning high energy physics graph neural network ln delta kt momentum"},
  {page:"research.html",pageLabel:"Research & Projects",title:"R3 — PINNs for Stochastic Inflation",
   snippet:"Physics-Informed Neural Networks (PINNs) for stochastic inflation in early universe cosmology. Solves differential equations governing inflationary dynamics. Supervisor: Dr. Rafid Mahbub.",
   keywords:"research r3 pinns physics-informed neural networks stochastic inflation early universe cosmology differential equations inflationary dynamics rafid mahbub exploratory"},
  {page:"research.html",pageLabel:"Research & Projects",title:"R4 — Gamma-Ray Burst ML (GRB-ML)",
   snippet:"Machine learning for GRB data and redshift estimation. Fermi telescope data, astrophysical feature engineering, transient phenomena classification. Supervisors: Dr. Soebur Razzaque, Dr. Saeeda Sajjad.",
   keywords:"research r4 gamma-ray burst grb ml machine learning redshift estimation fermi data transient astrophysics feature engineering soebur razzaque saeeda sajjad"},
  {page:"research.html",pageLabel:"Research & Projects",title:"R5 — RGC: Radio Galaxy Classifier",
   snippet:"Radha Gobinda Chandra: advanced ML classifier for radio galaxies from astronomical survey data. Deep learning, automated classification of bent radio AGN. CASSA project.",
   keywords:"research r5 rgc radio galaxy classifier radha gobinda chandra machine learning deep learning agn bent radio sources survey data computer vision cassa iub classification"},
  {page:"research.html",pageLabel:"Research & Projects",title:"R6 — RiFInE: Radio Frequency Interference Identification & Elimination",
   snippet:"Identifying and eliminating radio frequency interference (RFI) in astronomical observations. Signal processing, data quality improvement. Critical challenge in radio astronomy.",
   keywords:"research r6 rifine radio frequency interference rfi identification elimination mitigation signal processing data quality astronomical observations radio astronomy"},
  {page:"research.html",pageLabel:"Research & Projects",title:"Project — AstroPhotoZ: Photometric Redshift Estimation",
   snippet:"Photometric redshift estimation using machine learning and Gaussian Processes from astronomical survey data. Wi-STEM Bangladesh internship project.",
   keywords:"research project astrophotoz photometric redshift estimation machine learning gaussian processes astronomical survey data"},
  {page:"research.html",pageLabel:"Research & Projects",title:"Project — Bent Radio Galaxy Dataset",
   snippet:"Novel dataset for bent radio AGN morphology classification: NAT (Narrow Angle Tail) and WAT (Wide Angle Tail) galaxies. Used in IEEE ICIP 2025 publication.",
   keywords:"research project bent radio galaxy dataset nat narrow angle tail wat wide angle tail agn morphology classification"},
  {page:"research.html",pageLabel:"Research & Projects",title:"Ongoing Research Overview",
   snippet:"Research at the intersection of observation, computation, and theory: modified gravity, machine learning for astrophysics, radio astronomy, particle physics.",
   keywords:"research ongoing overview observation computation theory modified gravity machine learning astrophysics radio astronomy particle physics intersection"},

  /* ── ACADEMIC EXPERIENCE ── */
  {page:"academic_experience.html",pageLabel:"Academic Experience",title:"Research at CASSA — IUB",
   snippet:"Centre for Astro, Cosmology and Astrophysics Studies (CASSA), Independent University Bangladesh. Radio astronomy, machine learning for galaxy classification, RFI mitigation research.",
   keywords:"academic experience cassa centre astro cosmology astrophysics studies independent university bangladesh iub radio astronomy machine learning galaxy classification rfi mitigation"},
  {page:"academic_experience.html",pageLabel:"Academic Experience",title:"Research at CCDS — IUB",
   snippet:"Centre for Computational and Data Sciences (CCDS), Independent University Bangladesh. Research intern candidate. Deep learning code management, machine learning projects.",
   keywords:"academic experience ccds centre computational data sciences independent university bangladesh iub deep learning code management machine learning research intern candidate 2024"},
  {page:"academic_experience.html",pageLabel:"Academic Experience",title:"Teaching & Mentoring",
   snippet:"Teaching and mentoring experience in physics and astrophysics. Academic support and research guidance for undergraduate students at IUB.",
   keywords:"academic experience teaching mentoring physics astrophysics academic support research guidance undergraduate students iub"},
  {page:"academic_experience.html",pageLabel:"Academic Experience",title:"Independent University Bangladesh (IUB)",
   snippet:"Research and academic work at IUB. Department of Physical Sciences (DPS) and Computer Science & Engineering (CSE). Collaboration with faculty on cosmology, radio astronomy, machine learning.",
   keywords:"academic experience independent university bangladesh iub physical sciences dps computer science engineering cse faculty collaboration cosmology radio astronomy machine learning"},
  {page:"academic_experience.html",pageLabel:"Academic Experience",title:"Journal Talk — CASSA (2025)",
   snippet:"Journal Talk 2, CASSA, IUB (2025): Speaker on detecting radio frequency interference in radio sky imagery.",
   keywords:"academic experience journal talk cassa iub 2025 speaker radio frequency interference rfi detection sky imagery presentation"},

  /* ── ACHIEVEMENTS ── */
  {page:"achievements.html",pageLabel:"Achievements",title:"Dean's List — USM (Semesters II, III, VI)",
   snippet:"Dean's List awardee for outstanding academic achievement in Semesters II, III, and VI at Universiti Sains Malaysia.",
   keywords:"achievements dean's list usm universiti sains malaysia academic outstanding semesters ii iii vi award"},
  {page:"achievements.html",pageLabel:"Achievements",title:"BCGS Scholarship — University of Bonn (2026)",
   snippet:"Bonn-Cologne Graduate School of Physics and Astronomy (BCGS) Scholarship for Master's in Astrophysics at the University of Bonn, Germany (2026).",
   keywords:"achievements bcgs bonn cologne graduate school physics astronomy scholarship master's astrophysics university of bonn rheinische friedrich-wilhelms germany 2026"},
  {page:"achievements.html",pageLabel:"Achievements",title:"PSL University Master's Program — Paris (2026)",
   snippet:"Selected for Master's Program in Sciences of the Universe and Space Technologies (M1), PSL University, Paris, France (2026).",
   keywords:"achievements psl university paris master's sciences universe space technologies m1 france 2026 selected"},
  {page:"achievements.html",pageLabel:"Achievements",title:"Stipendium Hungaricum Scholarship (2024)",
   snippet:"Bangladesh Ministry of Education Nominee, Stipendium Hungaricum Scholarship (2024). Master's in Nuclear Energetics, Eötvös Loránd University & University of Pécs, Hungary.",
   keywords:"achievements stipendium hungaricum scholarship 2024 bangladesh ministry education master's nuclear energetics eotvos lorand university pecs hungary nominated"},
  {page:"achievements.html",pageLabel:"Achievements",title:"ICTP School — General Relativity & Cosmology (2025)",
   snippet:"ICTP PWF Bangladesh: School on General Relativity and Cosmology (2025), Participant.",
   keywords:"achievements ictp school general relativity cosmology 2025 pwf bangladesh participant international centre theoretical physics"},
  {page:"achievements.html",pageLabel:"Achievements",title:"ICTP School — Quantum Field Theory (2024)",
   snippet:"ICTP School on Quantum Field Theory 2024, PWF Bangladesh, Participant.",
   keywords:"achievements ictp school quantum field theory qft 2024 pwf bangladesh participant"},
  {page:"achievements.html",pageLabel:"Achievements",title:"CERN Summer Particle Astrophysics Workshop (2024)",
   snippet:"CERN Summer Particle Astrophysics Workshop 2024, Participant.",
   keywords:"achievements cern summer particle astrophysics workshop 2024 participant cern indico"},
  {page:"achievements.html",pageLabel:"Achievements",title:"NCTS-TCA Summer Student Program (2022)",
   snippet:"NCTS-TCA Summer Student Program, Online, 2022. Participant.",
   keywords:"achievements ncts tca summer student program online 2022"},
  {page:"achievements.html",pageLabel:"Achievements",title:"DPS IUB Summer School — Quantum World (2024)",
   snippet:"DPS IUB Summer School 2024: Glimpses into the Quantum World — Information, Technology, and Applications.",
   keywords:"achievements dps iub summer school 2024 quantum world information technology applications"},
  {page:"achievements.html",pageLabel:"Achievements",title:"Bangladesh Astro Olympiad — Champion (2014)",
   snippet:"9th Bangladesh Astro Olympiad Regional Round: Champion and Organizing Member (2014). National Round Participant, representing Faridpur.",
   keywords:"achievements bangladesh astro olympiad 9th regional champion organizing member 2014 national round faridpur"},
  {page:"achievements.html",pageLabel:"Achievements",title:"National Science & Technology Fair",
   snippet:"35th NSTF: Runner-up in Science Public Speaking (2014); School Representative. 36th NSTF: College Representative (2015).",
   keywords:"achievements national science technology fair 35th 36th runner-up science public speaking school college representative 2014 2015"},
  {page:"achievements.html",pageLabel:"Achievements",title:"Daily Star Spelling Bee — Winner (2013, 2014)",
   snippet:"The Daily Star Spelling Bee Regional Round Winner (2014) and Winner (2013).",
   keywords:"achievements daily star spelling bee regional round winner 2013 2014"},
  {page:"achievements.html",pageLabel:"Achievements",title:"Professional Memberships",
   snippet:"American Physical Society (APS) Member (2023–Present). Astronomy Club, Universiti Sains Malaysia (Exco 2019–2020). CASSA.",
   keywords:"achievements professional memberships american physical society aps member 2023 present astronomy club universiti sains malaysia exco 2019 2020 cassa"},
  {page:"achievements.html",pageLabel:"Achievements",title:"Radio Cosmology Workshop — University of Malaya (2023)",
   snippet:"Workshop on 'Decoding the Universe' 2023, organized by the Radio Cosmology Research Laboratory, University of Malaya.",
   keywords:"achievements decoding the universe workshop 2023 radio cosmology research laboratory university of malaya"},

  /* ── BLOG / NOTES ── */
  {page:"notes.html",pageLabel:"Blog",title:"Why Cosmology? — Personal Motivation",
   snippet:"On the questions that first pulled me toward studying the universe, and why I keep returning to them. A note for anyone wondering whether to chase the big questions.",
   keywords:"blog notes why cosmology personal motivation universe questions research career big questions curiosity"},
  {page:"notes.html",pageLabel:"Blog",title:"Lessons from My First Research Project",
   snippet:"What worked, what completely failed, and the things I wish someone had told me before sending my first email to a professor. Honest mistakes, research life, beginnings.",
   keywords:"blog notes lessons first research project professor honest mistakes beginnings research life email advice"},
  {page:"notes.html",pageLabel:"Blog",title:"On Failure and Slow Progress",
   snippet:"Most days in research don't feel like a discovery. Staying motivated when results take months or years. Resilience and mindset in academia.",
   keywords:"blog notes failure slow progress motivation resilience mindset process science research unglamorous academia"},
  {page:"notes.html",pageLabel:"Blog",title:"Balancing Curiosity and Output",
   snippet:"Chasing fascinating topics vs. real pressure to publish, ship code, and graduate. Career, curiosity, productivity tension.",
   keywords:"blog notes balancing curiosity output publish career productivity deep-vs-fast tension graduate academia"},
  {page:"notes.html",pageLabel:"Blog",title:"Study Notes — Cosmology & General Relativity",
   snippet:"Personal study notes on mathematical and physical foundations: General Relativity, Cosmology, Large-Scale Structure, Perturbation Theory, CMB physics.",
   keywords:"blog notes study cosmology general relativity large scale structure perturbation theory cmb physics mathematics foundations learning resources"},
  {page:"notes.html",pageLabel:"Blog",title:"Study Notes — Machine Learning in Physics",
   snippet:"Curated resources on machine learning for astrophysics: neural networks, Bayesian inference, Gaussian Processes, deep learning, graph neural networks.",
   keywords:"blog notes study machine learning physics astrophysics neural networks bayesian inference gaussian processes deep learning graph neural networks resources curated"},
  {page:"notes.html",pageLabel:"Blog",title:"Guides for Aspiring Researchers",
   snippet:"Practical guides covering how to find research opportunities, reach out to professors, read papers efficiently, and navigate the path toward a PhD.",
   keywords:"blog notes guides aspiring researchers phd research opportunities professors read papers efficiently navigate career advice practical"}
];
